app.py
from config import app
from flask import render_template
from routes.login import login_blueprint
from routes.inicio import inicio_blueprint
from routes.aluno import alunos_blueprint
from routes.turma import turmas_blueprint
from routes.professor import professores_blueprint

app.register_blueprint(login_blueprint, url_prefix="/login")
app.register_blueprint(inicio_blueprint, url_prefix="/inicio")
app.register_blueprint(alunos_blueprint, url_prefix="/aluno")
app.register_blueprint(turmas_blueprint, url_prefix="/turma")
app.register_blueprint(professores_blueprint, url_prefix="/professor")

app.secret_key = "@aula@api"

@app.route("/", methods=["GET",])
def index():
    return render_template("index.html")

if __name__ == '__main__':
  app.run(host=app.config["HOST"], port = app.config['PORT'],debug=app.config['DEBUG'] )

routes/aluno.py
from flask import Blueprint, render_template, jsonify, request, url_for, redirect, flash

alunos_blueprint = Blueprint("aluno", __name__)

import requests

#url = f'{ app.config["HOST_API"]}:{app.config["PORT_API"]}
url = 'http://127.0.0.1:8080'

@alunos_blueprint.route("/", methods=["GET"])
def index():
    retorno = requests.get(f'{url}/aluno/listar')
    return render_template("aluno/index.html", alunos = retorno.json())

@alunos_blueprint.route("/obter/<int:id>", methods=["GET"])
def obter(id):
    retorno = requests.get(f'{url}/aluno/obter/{id}')
    lista_turma = requests.get(f'{url}/turma/listar')
    return render_template("aluno/cadastrar.html", aluno = retorno.json(), turmas = lista_turma.json())


@alunos_blueprint.route("/cadastrar", methods=["GET"])
def cadastrar():
    lista_turma = requests.get(f'{url}/turma/listar')
    payload = {"id": 0, 
               "nome": "", 
               "idade": 0,
               "turma_id": 0,
               "data_nascimento": "",
               "nota_primeiro_semestre": "",
               "nota_segundo_semestre": ""
              } 
    
    return render_template("aluno/cadastrar.html", aluno = payload, turmas = lista_turma.json())

@alunos_blueprint.route("/salvar", methods=["POST"])
def salvar():
    payload = {"id": int(request.form["id"]), 
               "nome": request.form["nome"], 
               "turma_id": int(request.form["turma_id"]),
               "data_nascimento": request.form["data_nascimento"],
               "nota_primeiro_semestre": request.form["nota_primeiro_semestre"],
               "nota_segundo_semestre": request.form["nota_segundo_semestre"]
               }   

    if (payload["id"] == 0):
        retorno = requests.post(f"{url}/aluno/salvar", json = payload)
    else: 
        retorno = requests.post(f"{url}/aluno/alterar", json = payload)

    if (retorno.status_code == 200):
        dados = retorno.json()
        flash(dados.get('message'), "success")
        return redirect("/aluno/")
    else:
        flash("Não foi possível salvar", "alert")

@alunos_blueprint.route("/excluir", methods=["POST"])
def excluir():
    id = int(request.form["id"])

    payload = {"id": id }
    retorno = requests.post(f"{url}/aluno/excluir", json = payload)

    if (retorno.status_code == 200):
        dados = retorno.json()
        flash(dados.get('message'), "success")
        return redirect("/aluno/")
    else:
        flash("Não foi possível excluir", "alert")

routes/inicio.py
from flask import Blueprint, render_template

inicio_blueprint = Blueprint("inicio", __name__)

@inicio_blueprint.route("/")
def index():
    return render_template("inicio.html")

routes/login.py
from flask import Blueprint,render_template,jsonify, request, redirect

login_blueprint = Blueprint("login", __name__)

@login_blueprint.route("/", methods=["GET",])
def login():
    return render_template("login.html")

@login_blueprint.route("/logar", methods=["POST",])
def logar():
    usuario = request.form["usuario"]
    senha = request.form["senha"]
    return redirect("/inicio/")

@login_blueprint.route("/sair", methods=["GET",])
def sair():
    return redirect("/")

routes/professor.py
from flask import Blueprint, render_template, jsonify, request, url_for, redirect, flash

professores_blueprint = Blueprint("professor", __name__)

import requests

#url = f'{ app.config["HOST_API"]}:{app.config["PORT_API"]}
url = 'http://127.0.0.1:8080'

@professores_blueprint.route("/", methods=["GET"])
def index():
    retorno = requests.get(f'{url}/professor/listar')
    return render_template("professor/index.html", professores = retorno.json())

@professores_blueprint.route("/obter/<int:id>", methods=["GET"])
def obter(id):
    retorno = requests.get(f'{url}/professor/obter/{id}')
    return render_template("professor/cadastrar.html", professor = retorno.json())


@professores_blueprint.route("/cadastrar", methods=["GET"])
def cadastrar():
    return render_template("professor/cadastrar.html", professor = { "id": 0, "nome": "", "endereco": ""})

@professores_blueprint.route("/salvar", methods=["POST"])
def salvar():
  
    payload = {"id": int(request.form["id"]), 
               "nome": request.form["nome"], 
               "idade":  int(request.form["idade"]),
               "materia": request.form["materia"],
               "observacao":request.form["observacao"]
              }
    
    if (payload["id"] == 0):
        retorno = requests.post(f"{url}/professor/salvar", json = payload)
    else: 
        retorno = requests.post(f"{url}/professor/alterar", json = payload)

    if (retorno.status_code == 200):
        dados = retorno.json()
        flash(dados.get('message'), "success")
        return redirect("/professor/")
    else:
        flash("Não foi possível salvar", "alert")

@professores_blueprint.route("/excluir", methods=["POST"])
def excluir():
    payload = {"id": int(request.form["id"]) }
    retorno = requests.post(f"{url}/professor/excluir", json = payload)

    if (retorno.status_code == 200):
        dados = retorno.json()
        flash(dados.get('message'), "success")
        return redirect("/professor/")
    else:
        flash("Não foi possível excluir", "alert")

routes/turma.py
from flask import Blueprint, render_template, jsonify, request, url_for, redirect, flash

turmas_blueprint = Blueprint("turma", __name__)

import requests

#url = f'{ app.config["HOST_API"]}:{app.config["PORT_API"]}
url = 'http://127.0.0.1:8080'

@turmas_blueprint.route("/", methods=["GET"])
def index():
    retorno = requests.get(f'{url}/turma/listar')
    return render_template("turma/index.html", turmas = retorno.json())

@turmas_blueprint.route("/obter/<int:id>", methods=["GET"])
def obter(id):
    retorno = requests.get(f'{url}/turma/obter/{id}')
    lista_professor = requests.get(f'{url}/professor/listar')
    return render_template("turma/cadastrar.html", turma = retorno.json(), professores = lista_professor.json())

@turmas_blueprint.route("/cadastrar", methods=["GET"])
def cadastrar():
    lista_professor = requests.get(f'{url}/professor/listar')

    payload = {"id": 0,
               "descricao": "",
               "professor_id": 0, 
               "ativo": True
              }
    
    return render_template("turma/cadastrar.html", turma = payload, professores = lista_professor.json())

@turmas_blueprint.route("/salvar", methods=["POST"])
def salvar():

    payload = {"id": int(request.form["id"]),
                "descricao": request.form["descricao"],
                "professor_id": int(request.form["professor_id"]), 
                "ativo": "ativo" in request.form
              }
    
    if (payload["id"] == 0):
        retorno = requests.post(f"{url}/turma/salvar", json = payload)
    else: 
        retorno = requests.post(f"{url}/turma/alterar", json = payload)

    if (retorno.status_code == 200):
        dados = retorno.json()
        flash(dados.get('message'), "success")
        return redirect("/turma/")
    else:
        flash("Não foi possível salvar", "alert")

@turmas_blueprint.route("/excluir", methods=["POST"])
def excluir():
    id = int(request.form["id"])

    payload = {"id": id }
    retorno = requests.post(f"{url}/turma/excluir", json = payload)

    if (retorno.status_code == 200):
        dados = retorno.json()
        flash(dados.get('message'), "success")
        return redirect("/turma/")
    else:
        flash("Não foi possível excluir", "alert")

templates/aluno/cadastrar.html
{% extends "template.html" %}

{% block conteudo %}

<form action="{{url_for('aluno.salvar')}}" method="POST">
    <h2> Cadastro de Aluno/Cadastro </h2>
    
    <hr/>

    <div class="row">

        <input type="hidden" name="id" id="id" value="{{aluno.id}}"  />

        <div class="col-md-9 form-group">
            <label class="control-label">Nome</label>
            <input class="form-control" type="text" name="nome" id="nome" value="{{aluno.nome}}" required maxlength="99"/>
        </div>
    
        <div class="col-md-3 form-group">
            <label class="control-label">Idade</label>
            <input disabled class="form-control" type="text" name="idade" id="idade" value="{{aluno.idade}}" required />
        </div>

        <div class="col-md-6 form-group">
            <label class="control-label">Data de nascimento</label>
            <input class="form-control" type="date" name="data_nascimento" id="data_nascimento" value="{{aluno.data_nascimento_en_us}}" required />
        </div>

        <div class="col-md-6 form-group">
            <label class="control-label" name="ddlTurma" id="ddlTurma">Turma</label>
            <select class="form-control" name="turma_id" id="turma_id" required>
                <option value="">--Selecione--</option>
                {% for turma in turmas %}
                    {% if (aluno.turma_id == turma.id) %}
                        <option value="{{turma.id}}" selected = true>{{turma.descricao}}</option>
                    {% else %}
                        <option value="{{turma.id}}">{{turma.descricao}}</option>
                    {% endif %}
                {% endfor %}
            </select>
        </div>

        <div class="col-md-4 form-group">
            <label class="control-label">Nota do primeiro semestre</label>
            <input class="form-control" type="text" name="nota_primeiro_semestre" id="nota_primeiro_semestre" value="{{aluno.nota_primeiro_semestre}}" />
        </div>

        <div class="col-md-4 form-group">
            <label class="control-label">Nota do segundo semestre</label>
            <input class="form-control" type="text" name="nota_segundo_semestre" id="nota_segundo_semestre" value="{{aluno.nota_segundo_semestre}}" />
        </div>

        <div class="col-md-4 form-group">
            <label class="control-label">Média final</label>
            <input disabled class="form-control" type="text" name="media_final" id="media_final" value="{{aluno.media_final}}" />
        </div>
    </div>    

    <hr/>

    <div class="row">
        <input type="submit" class="btn btn-success" id="btnset" value="Salvar" /> 
    </div>
        
</form>

{% endblock %}

templates/aluno/index.html
{% extends "template.html" %}

{% block conteudo %}

<h2> Cadastro de Aluno/Listar </h2>

<hr/>

<div class="row">
    <a class="btn btn-primary" href="cadastrar">Cadastrar</a>
</div>

<table class="table table-striped table-bordered table-hover">
   <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nome</th>
        <th scope="col">Idade</th>
        <th scope="col">Turma</th>
        <th scope="col">Data de nascimento</th>
        <th scope="col">Nota do primeiro semestre</th>
        <th scope="col">Nota do segundo semestre</th>
        <th scope="col">Média final</th>
        <th scope="col">Ação</th>
      </tr>
    </thead>
    <tbody>

        {% for aluno in alunos %}
        <tr>
            <th scope="row">{{aluno.id}}</th>
            <td>{{aluno.nome}}</td>
            <td>{{aluno.idade}}</td>
            <td>{{aluno.turma_nome}}</td>
            <td>{{aluno.data_nascimento_pt_br}}</td>
            <td>{{aluno.nota_primeiro_semestre}}</td>
            <td>{{aluno.nota_segundo_semestre}}</td>
            <td>{{aluno.media_final}}</td>

            <td> <a class="btn btn-warning" href="obter/{{aluno.id}}">Alterar</a>                
                <form action="excluir" method="POST">
                    <input type="hidden" name="id" id="id" value="{{aluno.id}}" />
                    <input type="submit" class="btn btn-danger" value="Excluir" onclick="return confirm('Tem certeza de deseja excluir?')" /> 
                </form>
            </td>
          </tr>

        {% endfor %}

    </tbody>
  </table>

{% endblock %}

templates/index.html
<html>

<header>
    <title>Site</title>
</header>

<body>
    <h1>site aberto (não logado)</h1>
    
    <a href="/login/">logar aqui</a>
</body>

</html>

templates/inicio.html
{% extends "template.html" %}

{% block conteudo %}

<h1> inicio logado </h1>

{% endblock %}

templates/login.html
<html>

<header> 
<title>Acesso restrito</title>

<style>

.login-page {
  width: 360px;
  padding: 8% 0 0;
  margin: auto;
}
.form {
  position: relative;
  z-index: 1;
  background: #FFFFFF;
  max-width: 360px;
  margin: 0 auto 100px;
  padding: 45px;
  text-align: center;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
}
.form input {
  font-family: "Roboto", sans-serif;
  outline: 0;
  background: #f2f2f2;
  width: 100%;
  border: 0;
  margin: 0 0 15px;
  padding: 15px;
  box-sizing: border-box;
  font-size: 14px;
}
.form button {
  font-family: "Roboto", sans-serif;
  text-transform: uppercase;
  outline: 0;
  background: #0a58ca;
  width: 100%;
  border: 0;
  padding: 15px;
  color: #FFFFFF;
  font-size: 14px;
  -webkit-transition: all 0.3 ease;
  transition: all 0.3 ease;
  cursor: pointer;
}

</style>

</header>

<body>

    <div class="login-page">
        <div class="form">
            <h1>Acesso restrito</h1>
            <form class="login-form"  action="/login/logar" method="POST">
            <input type="text" placeholder="login" name="usuario" required />
            <input type="password" placeholder="senha" name="senha" required/>
            <button>Entrar</button>
            </form>
        </div>
    </div>

</body>

</html>

templates/professor/cadastrar.html
{% extends "template.html" %}

{% block conteudo %}

<form action="{{url_for('professor.salvar')}}" method="POST">
    <h2> Cadastro de Professor/Cadastro </h2>

    <hr/>

    <div class="row">
        <input type="hidden" name="id" id="id" value="{{professor.id}}"  />

        <div class="col-md-9 form-group">
            <label class="control-label">Nome</label>
            <input class="form-control" type="text" name="nome" id="nome" value="{{professor.nome}}" required maxlength="99"/>
        </div>
    
         <div class="col-md-3 form-group">
            <label class="control-label">Idade</label>
            <input class="form-control" type="number" name="idade" id="idade" value="{{professor.idade}}" required />
        </div>

        <div class="col-md-6 form-group">
            <label class="control-label">Matéria</label>
            <input class="form-control" type="text" name="materia" id="materia" value="{{professor.materia}}" required maxlength="99" />
        </div>

        <div class="col-md-6 form-group">
            <label class="control-label">Observação</label>
            <input class="form-control" type="text" name="observacao" id="observacao" value="{{professor.observacao}}" required maxlength="199" />
        </div>
    </div>    

    <hr/>

    <div class="row">
        <input type="submit" class="btn btn-primary" id="btnset" value="Salvar" /> 
    </div>
        
</form>

{% endblock %}

templates/professor/index.html
{% extends "template.html" %}

{% block conteudo %}

<h2> Cadastro de Professor/Listar </h2>

<hr/>

<div class="row">
    <a class="btn btn-primary" href="cadastrar">Cadastrar</a>
</div>

<table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nome</th>
        <th scope="col">Idade</th>
        <th scope="col">Matéria</th>
        <th scope="col">Observação</th>
        <th scope="col">Ação</th>
      </tr>
    </thead>
    <tbody>

        {% for professor in professores %}
        <tr>
            <th scope="row">{{professor.id}}</th>
            <td>{{professor.nome}}</td>
            <td>{{professor.idade}}</td>
            <td>{{professor.materia}}</td>
            <td>{{professor.observacao}}</td>
            
            <td> <a class="btn btn-warning" href="obter/{{professor.id}}">Alterar</a>                
                <form action="excluir" method="POST">
                    <input type="hidden" name="id" id="id" value="{{professor.id}}" />
                    <input type="submit" class="btn btn-danger" value="Excluir" onclick="return confirm('Tem certeza de deseja excluir?')" /> 
                </form>
            </td>
          </tr>

        {% endfor %}

    </tbody>
  </table>

{% endblock %}

templates/template.html
<!doctype html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Sistema Escola</title>

    <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/site.css')}}">

    <script src="{{url_for('static',filename='js/bootstrap.min.js')}}"></script>

  </head>
  <body>

    <div class="container">
        {% for message in get_flashed_messages(): %}
            <div class="alert alert-success" role="alert">
                {{message}}
            </div>
        {% endfor %}

        <h1 class="bg-light text-center text-primary">Sistema de Gestão Escolar</h1>

        <nav class="navbar navbar-expand-lg navbar-info bg-info">
            <a class="navbar-brand" href="{{url_for('inicio.index')}}">Escola</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('professor.index') }}">Cadastro de Professor</a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{{ url_for('turma.index') }}">Cadastro de Turma </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('aluno.index') }}">Cadastro de Aluno</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('login.sair') }}">Sair</a>
                </li>
              </ul>
            </div>
          </nav>
        
        {% block conteudo %}
        {% endblock %}
    </div>

  </body>
</html>

templates/turma/cadastrar.html
{% extends "template.html" %}

{% block conteudo %}

<form action="{{url_for('turma.salvar')}}" method="POST">
    <h2> Cadastro de Turma/Cadastro </h2>
    
    <hr/>
    
    <div class="row">
        <input type="hidden" name="id" id="id" value="{{turma.id}}"  />
    
        <div class="col-md-6 form-group">
            <label class="control-label">Descrição</label>
            <input class="form-control" type="text" name="descricao" id="descricao" value="{{turma.descricao}}" required maxlength="199" />
        </div>

        <div class="col-md-6 form-group">
            <label class="control-label" name="ddlProfessor" id="ddlProfessor">Professor</label>
            <select class="form-control" name="professor_id" id="professor_id" required>
                <option value="">--Selecione--</option>
                {% for professor in professores %}
                    {% if (turma.professor_id == professor.id) %}
                        <option value="{{professor.id}}" selected = true >{{professor.nome}}</option>
                    {% else %}
                        <option value="{{professor.id}}">{{professor.nome}}</option>
                    {% endif  %}
                {% endfor %}
            </select>
        </div>

        <div class="col-md-6 form-group">
            <label class="control-label">Ativo</label><br/>
            <input class="form-check-input" type="checkbox" name="ativo" id="ativo" 
            {% if turma.ativo %}checked{% endif %} />
             </div>

    </div>   

    <hr/>

    <div class="row">
        <input type="submit" class="btn btn-success" id="btnset" value="Salvar" /> 
    </div>
        
</form>

{% endblock %}

templates/turma/index.html
{% extends "template.html" %}

{% block conteudo %}

<h2> Cadastro de Turma/Listar </h2>

<hr/>

<div class="row">
    <a class="btn btn-primary" href="cadastrar">Cadastrar</a>
</div>

<table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Descrição</th>
        <th scope="col">Professor</th>
        <th scope="col">Ativo</th>
        <th scope="col">Ação</th>
      </tr>
    </thead>
    <tbody>

        {% for turma in turmas %}
        <tr>
            <th scope="row">{{turma.id}}</th>
            <td>{{turma.descricao}}</td>
            <td>{{turma.professor_nome}}</td>
            <td>{% if turma.ativo %}
                <span>Sim</span>
                {% else %}
                <span>Não</span>
                {% endif %}
            </td>

            <td> <a class="btn btn-warning" href="obter/{{turma.id}}">Alterar</a>   
                <form action="excluir" method="POST">
                    <input type="hidden" name="id" id="id" value="{{turma.id}}" />
                    <input type="submit" class="btn btn-danger" value="Excluir" onclick="return confirm('Tem certeza de deseja excluir?')" /> 
                </form>
            </td>
          </tr>

        {% endfor %}

    </tbody>
  </table>

{% endblock %}